FROM python:3.6

# Set the working directory to /app
WORKDIR /test

# Copy the current directory contents into the container at /app
COPY . /test

# Run app.py when the container launches
CMD ["python", "hello.py"]
